### ISSUE TITLE
cocoapods

### ISSUE THREAD

**Issue by espeneric** [fluthaus/NHBRuuviKit#1]
nice library. Will you be integrating it with cocoapods?

**Comment by NoHalfBits** [comment]
maybe, when I find the time... but it 's low on the priority list.

**Comment by NoHalfBits** [comment]
Added podspec and pushed it to trunk.

I should probably mention that I'm not a fan of CocoaPods, do not use them in my projects, and never published a pod before. Following the guides, it seems to work, but if you find any issues, please feel free to open an issue, suggest improvements and kindly bear with me.

Btw., I noticed `pod try`, but supporting it seems to require changes which will break the sample project for all other users. So for now, it's just the dependency management for the framework.
